app = "tfg-recommender-backend"
primary_region = "cdg"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  SQLITE_FILE_NAME = "/app/data/database.db"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = "tfg_data"
  destination = "/app/data"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
